name: Process URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to process'
        required: true
        type: string
      toreaddir:
        description: 'Directory where articles to read are stored'
        required: false
        type: string
        default: _toread
      model:
        description: 'OpenAI model to use for summarization'
        required: false
        type: string
        default: gpt-3.5-turbo

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install llm beautifulsoup4 requests pyyaml validators playwright slugify
          playwright install chromium

      - name: Process URL
        id: process_url
        run: |
          python scripts/process_url_workflow/url_processor.py "${{ github.event.inputs.url }}" "${{ github.event.inputs.toreaddir }}" "${{ github.event.inputs.model }}"
        env:
          PYTHONUNBUFFERED: 1
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Configure git
        if: steps.process_url.outputs.existing_file == ''
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Commit changes
        if: steps.process_url.outputs.existing_file == ''
        run: |
          git add "${{ github.event.inputs.toreaddir }}/${{ steps.process_url.outputs.filename }}"
          git commit -m "Add new link: ${{ steps.process_url.outputs.title }}"

      - name: Validate new files
        if: steps.process_url.outputs.existing_file == ''
        run: python scripts/process_url_workflow/frontmatter_validator.py "${{ github.event.inputs.toreaddir }}"
      
      - name: Push changes
        if: steps.process_url.outputs.existing_file == ''
        run: |
          git push origin main 